nordic-institute/X-Road-Metrics

opendata_module/opmon_opendata/api/apps.py, opendata_module/opmon_opendata/django_settings.py, opendata_module/opmon_opendata/gui/apps.py
This change is needed for django 3.2 while updating packages to ubuntu 22.04
=> [Opmondev-156]: fix django apps config 

anonymizer_module/setup.py, collector_module/setup.py, corrector_module/setup.py, opendata_module/setup.py
https://nordic-institute.atlassian.net/wiki/spaces/OPMONDEV/pages/146931713/Python+Dependencies+Vulnerability+Check
`urllib3` 1.25.11 -> 1.26.14
`pyyaml` 5.3.1 -> 5.4.1
`setuptools` 56.0.0 -> 67.4.0
=> [Opmondev-157]: update vulnerable python dependencies

anonymizer_module/opmon_anonymizer/iio/postgresql_manager.py, opendata_module/opmon_opendata/api/postgresql_manager.py
Changes are done to `anonymizer_module and  `opendata_module`.
=> [Opmondev-139]:  parametrise SQL queries to avoid SQL injections

collector_module/etc/settings.yaml, collector_module/opmon_collector/collector_worker.py, collector_module/opmon_collector/tests/test_collector_worker.py
Based on https://github.com/nordic-institute/X-Road-Metrics/pull/17
=> Improve collector logging of records to file

anonymizer_module/opmon_anonymizer/iio/postgresql_manager.py, opendata_module/opmon_opendata/api/postgresql_manager.py
Additionally: revert https://github.com/nordic-institute/X-Road-Metrics/pull/30 part for `opendata_module`
=> [Opmondev-159]: fix anonymizer failed connectto PostgresSQL DB

opendata_collector_module/metrics_opendata_collector/main.py, opendata_collector_module/metrics_opendata_collector/opendata_collector.py, opendata_collector_module/metrics_opendata_collector/settings.py, opendata_collector_module/metrics_opendata_collector/tests/settings_TEST.yaml, opendata_collector_module/metrics_opendata_collector/tests/test_main.py, opendata_collector_module/metrics_opendata_collector/tests/test_opendata_sources_settings.yaml, opendata_collector_module/setup.py, opendata_collector_module/test_requirements.txt, opendata_collector_module/tox.ini
https://nordic-institute.atlassian.net/browse/OPMONDEV-161
=> [OPMONDEV-161]: create opendata_collector_module and parse settings

opendata_module/opmon_opendata/api/views.py, opendata_module/opmon_opendata/tests/test_api.py
https://nordic-institute.atlassian.net/browse/OPMONDEV-162
Column names will be used to store data to MongoDB
=> [OPMONDEV-162]: return list of columns along with OpenData rows

opendata_collector_module/metrics_opendata_collector/mongodb_manager.py
This field is needed for Anonymizer to set state of last inserted entry.
This allows to anonymize only not yet anonymized entries.
=> [OPMONDEV-165]: add insertTime to OpenData

anonymizer_module/opmon_anonymizer/anonymizer.py, anonymizer_module/opmon_anonymizer/external_files/create_indices.py, anonymizer_module/opmon_anonymizer/iio/mongodbmanager.py, anonymizer_module/opmon_anonymizer/main.py, anonymizer_module/opmon_anonymizer/opendata_anonymizer.py, anonymizer_module/opmon_anonymizer/tests/manual/drop_example_table.py, anonymizer_module/opmon_anonymizer/tests/test_anonymizer.py, anonymizer_module/opmon_anonymizer/tests/test_main.py, anonymizer_module/opmon_anonymizer/tests/test_opendata_anonymizer.py, anonymizer_module/test_requirements.txt, anonymizer_module/tox.ini
Anonymize Opendata.
This is done by adding  optional parameter`--only_opendata` to anonymizer executable.
=> [Opmondev-165]:  anonymize Opendata

collector_module/opmon_collector/central_server_client.py, collector_module/opmon_collector/collector_multiprocessing.py, collector_module/opmon_collector/collector_worker.py, collector_module/opmon_collector/database_manager.py, collector_module/opmon_collector/logger_manager.py, collector_module/opmon_mongodb_maintenance/create_indexes.py, collector_module/opmon_mongodb_maintenance/create_users.py, collector_module/opmon_mongodb_maintenance/main.py
1. Use 'logging.exception()`  while handling exceptions.
2. Use `logging` instead of `print()`
=> [OPMONDEV-168]: improve error handling in collector_module

anonymizer_module/opmon_anonymizer/anonymizer.py, anonymizer_module/opmon_anonymizer/external_files/create_indices.py, anonymizer_module/opmon_anonymizer/iio/mongodbmanager.py, anonymizer_module/opmon_anonymizer/iio/postgresql_manager.py, anonymizer_module/opmon_anonymizer/main.py, anonymizer_module/opmon_anonymizer/opendata_anonymizer.py, anonymizer_module/opmon_anonymizer/tests/manual/drop_example_table.py, anonymizer_module/opmon_anonymizer/utils/logger_manager.py
1. use `logger.exception()` while handling exeptions.
2. use `logging` instead of `print()`
=> [OPMONDDEV-168]: improve error handling in anonymizer_module

corrector_module/opmon_corrector/corrector_batch.py, corrector_module/opmon_corrector/correctord.py, corrector_module/opmon_corrector/database_manager.py, corrector_module/opmon_corrector/logger_manager.py
Use `logger.exception()` while handling exceptions
=> [OPMONDEV-168]: improve error handling for corrector_module

opendata_module/opmon_opendata/api/views.py, opendata_module/opmon_opendata/gui/views.py, opendata_module/opmon_opendata/logger_manager.py, opendata_module/opmon_opendata/tests/manual/drop_example_table.py, opendata_module/opmon_opendata/tests/test_api.py
1. Use `logger.exception()` while handling exceptions.
2. Use `logging` instead of `print()`
3. Use absolute imports. 
4. Fix broken tests
=> [OPMONDDEV-168]: improve error handling in opendata_module

opendata_collector_module/metrics_opendata_collector/logger_manager.py, opendata_collector_module/metrics_opendata_collector/opendata_collector.py
Use `logger.exception()` while handling exceptions.
=> [OPMONDEV-168]: improve error handling for opendata_collector_module

opendata_module/opmon_opendata/api/helpers.py, opendata_module/opmon_opendata/api/views.py
1. Move `api.views.py` helpers to `api.helpers.py`
2. Add missing types
=> [OPMONDEV-171]: code clean up

corrector_module/opmon_corrector/corrector_batch.py, corrector_module/opmon_corrector/document_manager.py, corrector_module/opmon_corrector/tests/test_document_manager.py, corrector_module/setup.py
https://nordic-institute.atlassian.net/browse/OPMONDEV-138
MongoDB in Metrics has no any user input. Data comes from Security servers, which can be compromised potentially.
This change will sanitise  injected  JavaScript  code .
=> [OPMONDEV-138]: sanitise documents before processing it in corrector module

opendata_module/opmon_opendata/api/postgresql_manager.py
Currently opendata is fetching daily logs from DB without using server side cursors. That means that python application may need to load gigabytes of data info memory before it starts streaming the result to the browser.
The proposed solution is to use server side cursors: https://www.psycopg.org/docs/usage.html#server-side-cursors
After the change application would fetch data from DB in small batches, and would be able to run on a server with a low amount of RAM.
=> Opendata memory usage optimization

README.md
Updates links related to the service desk change. I also noticed our JIRA links were not up to date.
+ some minor formatting changes.
=> chore: update service desk and JIRA links

docs/experimental/analysis_module.md, docs/experimental/analysis_module/analyzer_installation.md, docs/experimental/analysis_module/ui_installation.md, docs/reports_module.md, docs/system_architecture.md
- Add support for Ubuntu 22.04 where it's still missing.
=> docs: Documentation updates

anonymizer_module/etc/settings.yaml, docs/opendata_module.md
Fixed the default settings file for the anonymizer statistics module. Also updated the Postgres settings instructions a bit so that they would be clearer.
=> Updates for Metrics release 1.2.0

anonymizer_module/etc/settings.yaml, docs/opendata_module.md
* chore: fix the incorrect name in sample settings.yaml
* chore: improve documentation example
=> Updates for Metrics release 1.2.0 (#95)

anonymizer_module/metrics_statistics/mongodb_manager.py, anonymizer_module/test_requirements.txt, opendata_collector_module/test_requirements.txt, opendata_module/test_requirements.txt
=> chore: remove unnecessary test-dependency (pymongo-stubs)

analysis_module/Makefile, analysis_ui_module/Makefile, anonymizer_module/Makefile, collector_module/Makefile, corrector_module/Makefile, opendata_collector_module/Makefile, opendata_module/Makefile, reports_module/Makefile
=> chore: Update "make clean" command to clean test_results.xml and related htmlcov folder

anonymizer_module/Makefile
=> fix: Add missing make license command in anonymizer module

README.md, docs/dev_guide/developer_guide.md
This PR creates this [Developer's Guide](https://github.com/nordic-institute/X-Road-Metrics/blob/developers-guide/docs/dev_guide/developer_guide.md)
=> docs: Add Developer's Guide documentation

.ort.yml
- Update path excludes.
- Remove Maven-specific scope excludes.
=> chore: Update ORT config

anonymizer_module/opmon_anonymizer/__init__.py, collector_module/opmon_collector/__init__.py, corrector_module/opmon_corrector/__init__.py, opendata_collector_module/metrics_opendata_collector/__init__.py, opendata_module/opmon_opendata/__init__.py, reports_module/opmon_reports/__init__.py
=> chore: bump version to 1.4.0
