nordic-institute/X-Road-Metrics

docs/opendata_module.md

The locale en_US.UTF-8 needs to be available before the database can be initialised.

Add information about setting the locale first

---

CONTRIBUTING.md

Add CONTRIBUTING.md guidelines to the repository, linking it to the core X-Road repository guidelines.

Add CONTRIBUTING.md guidelines to the repository

---

anonymizer_module/etc/settings.yaml
anonymizer_module/opmon_anonymizer/iio/postgresql_manager.py
docs/anonymizer_module.md
docs/networking_module.md
docs/opendata_module.md
networking_module/etc/settings.yaml
networking_module/prepare_data.R
opendata_module/etc/settings.yaml
opendata_module/opmon_opendata/api/postgresql_manager.py

Changes are done to `anonymizer`, `opendata` and  `networking` modules.
1. Add entry to settings file to enable `sslmode`
2. Add entry to settings file to set path for SSL root certificate
3. Configure `psycopg2` (PostgreSQL python client) to initiate secure SSL connection in `anonymizer` and `opendata` modules.
4.  Configure `RPostgreSQL` (R PostgreSQL client) to initiate SSL connection in `networking` module
5. Update documentation to reflect give changes.

Opmondev-150: make TLS connection to PostgreSQL from db clients available

---

anonymizer_module/etc/settings.yaml
anonymizer_module/opmon_anonymizer/iio/mongodbmanager.py
collector_module/etc/settings.yaml
collector_module/opmon_collector/database_manager.py
corrector_module/etc/settings.yaml
corrector_module/opmon_corrector/database_manager.py
docs/database_module.md
reports_module/etc/settings.yaml
reports_module/opmon_reports/mongodb_handler.py

This change effects `anonymizer`, `collector`, `corrector` and `reports`  modules.
1. Add entry `tls` to settings file to enable `TLS`.
2. Add entry to settings file to set path for SSL certificate `tls-ca-file`.
3. Configure `pymongo` (MongoDB python client) to initiate secure SSL connection.
Update documentation to reflect give changes.

Opmondev-147:  make TLS connection to MongoDB from db clients possible

---

collector_module/etc/settings.yaml
collector_module/opmon_collector/collector_worker.py
docs/collector_module.md

This change effects only `collector` module.
1. Set up python `requests` library to use mTLS
2. Add related entries to `settings.yaml` 
3. Update documentation how to fill configuration.

OPMONDEV-148: make mTLS connection available for collector module

---

networking_module/etc/settings.yaml
networking_module/prepare_data.R

* R library RPostgreSQL does not support partial fetching of results
* Replacing RPostgreSQL with RODBC library
* Fetching data in configurable batch sizes to lower memory usage
* Adding configuration parameter
* Packaging is out of scope of this commit
It is required to remove package dependancy r-cran-rpostgresql and
r-cran-dbi(?) and add r-cran-rodbc and odbc-postgresql
* Fixes issue https://github.com/nordic-institute/X-Road-Metrics/issues/7
Performance test:
Rows in sample dataset: 20 205 229
Old code (fetches all data into memory)
Mem Used: 7G
Time: 4m7s
New code, fetch Size: 100 000
Mem Used: 201M
Time: 2m53s
New code, fetch Size: 1 000 000:
Mem Used: 538M
Time: 2m45s
New code, fetch Size: 10 000 000:
Mem Used: 4.1G
Time: 2m53s

Networking memory usage optimization

---

docs/anonymizer_module.md
docs/collector_module.md
docs/corrector_module.md
docs/database_module.md
docs/networking_module.md
docs/opendata_module.md
docs/reports_module.md

1. Update outdated documentation for `corrector_module`
2. Fix broken Markdown links

[OPMONDEV-158]: fix documentation links and update corrector documentation

---

docs/anonymizer_module.md
docs/collector_module.md
docs/corrector_module.md
docs/database_module.md
docs/networking_module.md
docs/opendata_module.md

Update documentation to support installation of Metrics on Ubuntu 22.04

[OPMONDEV-156]: update documentation to install Metrics on Ubuntu 22.04

---

opendata_module/opmon_opendata/django_settings.py

Missing comma added to Django settings

[OPMONDEV-158]: fix Django settings error

---

opendata_module/opmon_opendata/tests/test_logger_manager.py

This PR tests if https://github.com/nordic-institute/X-Road-Metrics/pull/14/files
fixes logger handler duplication
Given PR should be merged

Test opendata_module logger handler is not duplicated

---

opendata_module/opmon_opendata/logger_manager.py

Currently check `handler is WatchedFileHandler` always fails and a new handler is added before every write to the log. First log line gets logged once, second line twice, tenth line ten times and so on.
The proposed fix is to use `isinstance(handler, WatchedFileHandler)`.
For example:
```
python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
>>> from logging.handlers import WatchedFileHandler
>>> handler = WatchedFileHandler('/tmp/log')
>>> handler is WatchedFileHandler
False
>>> isinstance(handler, WatchedFileHandler)
True
```

Fix duplicate logging

---

collector_module/etc/settings.yaml
collector_module/opmon_collector/collector_worker.py

* Adding configurable support to save collected logs to files
* Adding configuration examples
Currently collector saves logs into database, and if you need to backup collected data as files, then a separate collector software is required. In order to simplify setup and avoid duplicate collector queries it is useful to be able to save collected data to files in addition to database.

Save collected logs to files

---

reports_module/etc/settings.yaml
reports_module/opmon_reports/notification_manager.py

* adding configuration parameters for providing TLS certfile and keyfile
* adding certificate and key files to SSLContext
Currently it is not possible to use client TLS authentication for sending e-mails, but some smtp services require client certificates.

SMTP Client TLS Authentication support for Reports

---

opendata_module/opmon_opendata/api/forms.py
opendata_module/opmon_opendata/tests/test_api.py
opendata_module/setup.py
opendata_module/test_requirements.txt
opendata_module/tox.ini

1. `JSONField` was introduced in Django 3.1
https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.JSONField
2. Date and time iso format was not included in `forms.DateTimeField`  `input_formats ` in Django 2.2.28
3. Add  test env in tox.ini to cover test cases for legacy Django 2.2.28

[Opmondev -162]: opendata_module: fix Django 2.2.28 and Django 3.2.18 compatibility issue

---

opendata_module/opmon_opendata/api/forms.py
opendata_module/opmon_opendata/api/postgresql_manager.py
opendata_module/opmon_opendata/api/views.py
opendata_module/opmon_opendata/tests/test_api.py
opendata_module/setup.py
opendata_module/test_requirements.txt

1. Return `total_query_count`. It allows to define if pagination is needed
2. Use `from_row_id` for querying. It allows to filter logs more precisely.
3. Use timezone to prepare timestamps for querying. Each timestamp in logs are generated taking timezone into account

[OPMONDEV-162]: Fix /api/harvest endpoint to return relevant data

---

opendata_module/opmon_opendata/api/forms.py
opendata_module/opmon_opendata/api/views.py
opendata_module/opmon_opendata/tests/test_api.py
opendata_module/setup.py

1. Use date time strings with timezone offset instead of `timestamp_tz`
2. Return timestamp timezone offset in response data

[Opmondev-162]: use date time strings with timezone offset

---

opendata_module/opmon_opendata/api/forms.py
opendata_module/opmon_opendata/tests/test_api.py

The problem: `+` sign is replaced with space in HTTP, because it is a reserved symbol.
When we pass 'from_dt': '2022-11-07T07:00:00+0000' to url, Django will raise a `ValueError` because datetime object can't be build using string '2022-11-07T07:00:00 0000'.
There were an option to encode passed query params and than to decode it in Django views and pass it to the form. In this way `+` should be preserved. Maybe.
I choose more easiest way, because don't want to spend more time on this problem today and fix it in correct way later.
1. Use `CharField` instead of `DateTimeField`
2. Replace empty string in with `+` sign if such case exists
3. Check if given datetime string is valid and can be used to construct a datetime object

[Opmondev-162]: use CharField instead of DateTimeField to fix replaced plus sign

---

opendata_collector_module/metrics_opendata_collector/opendata_api_client.py
opendata_collector_module/metrics_opendata_collector/opendata_collector.py
opendata_collector_module/metrics_opendata_collector/tests/test_opendata_collector.py

1. Reduce log entries by removing "inserted n opendata documents into MongoDB". We still have log entry about totals
2. Rename functions: `_do_request()` ->  `get_opendata()` and `get_opendata()` ->  `do_request()`

[Opmondev-163]:  minor fixes

---

opendata_module/opmon_opendata/api/views.py
opendata_module/opmon_opendata/tests/test_api.py

Log entry: "received 102 rows from total 2902 within range 2801-3000", "version": "0.1.0"}"
Incorrect:   within range 2801-3000
Correct:  within range 2801-2903

Opmondev-162]:  fix Opendata row range when returned rows are less than limit

---

collector_module/opmon_mongodb_maintenance/create_indexes.py
collector_module/opmon_mongodb_maintenance/create_users.py
collector_module/opmon_mongodb_maintenance/main.py
collector_module/opmon_mongodb_maintenance/tests/test_create_users.py
docs/database_module.md
docs/opendata_collector_module.md

We don't want providers to create opendata_collector MongoDB user created by running DB initialisation  script.
Only Metrics Platform admin creates it using new parameter `--user-to-generate`:
```
xroad-metrics-init-mongo --host xroad-metrics-centraldb:27017 --user root --password mysecret EX --user-to-generate opendata_collector
```

Metrics POC: do not create opendata_collector MongoDB user automatically

---

networking_module/prepare_data.R

[OPMONDEV-167](https://nordic-institute.atlassian.net/browse/OPMONDEV-167)
Fixes issue https://github.com/nordic-institute/X-Road-Metrics/issues/41
This fix was tested.
1. Pass `settings$postgres$ssl_mod` directly to `odbcDriverConnect()`
2. Set ENV variable `PGSSLROOTCERT`  only when `ssl_root_cert` is set. Otherwise use default system cert.
[OPMONDEV-167]: https://nordic-institute.atlassian.net/browse/OPMONDEV-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OPMONDEV-167]: fix SSL mode setting for RODBC

---

opendata_module/opmon_opendata/tests/test_api.py
opendata_module/opmon_postgresql_maintenance/create_users.py
opendata_module/tox.ini

https://nordic-institute.atlassian.net/browse/OPMONDEV-149
1. Add optional parameter `--remove-existing-users`, which removes existing associated DB users before creating new ones.
2. Use transaction while creating new users. In case of failure none users will be created.

[OPMONDEV-149]:  Opendata: improve PG init script to be able rerun it in case of error

---

anonymizer_module/etc/settings.yaml
anonymizer_module/metrics_statistics/central_server_client.py
anonymizer_module/metrics_statistics/mongodb_manager.py
anonymizer_module/metrics_statistics/postgresql_manager.py
anonymizer_module/metrics_statistics/statistics_manager.py
anonymizer_module/metrics_statistics/tests/test_statistics_manager.py
anonymizer_module/test_requirements.txt

1.  Count member classes: `member_gov_count`, `member_com_count` and `member_org_count`. - taken from global configuration. This configuration comes from security server.
2. Count services. List of unique services taken from `LOGS`  and strored in PG as `service_count`.
3. Count service requests in MongoDB and strore as `services_request_counts` JSON field.   List of service count can be limited by `settings['metrics-statistics'][num-max-services-requests]`. List of service counts is sorted by counts.

[OpMONDEV-179]: add member and service data to metrics statistics

---

anonymizer_module/metrics_statistics/central_server_client.py
anonymizer_module/metrics_statistics/mongodb_manager.py
anonymizer_module/metrics_statistics/postgresql_manager.py
anonymizer_module/metrics_statistics/statistics_manager.py
anonymizer_module/metrics_statistics/tests/test_statistics_manager.py
opendata_module/opmon_opendata/api/postgresql_manager.py
opendata_module/opmon_opendata/api/views.py
opendata_module/opmon_opendata/tests/test_api.py
opendata_module/opmon_opendata/tests/test_utils.py

As Petteri and Raido raised a question about member data being in dynamic nature and each instance may have own:
1. Use single `member_count` JSON field in PG to store dynamic result of count.
2. Take members from global configuration and count occurrences in member list
3. Store description of member class as well
4. Additionally unify service count data, stored in PG.
5. Change Opendata module API to return updated statistics structure.
At the end, data returned in Opendata  GET `api/statistics` looks correspondingly :
```
{
"current_month_request_count": 18928,
"current_year_request_count": 42099,
"previous_month_request_count": 20174,
"previous_year_request_count": 0,
"today_request_count": 0,
"total_request_count": 42099,
"member_count": [
{
"class_name": "COM",
"description": …
```

[OPMONDEV-179]:  make member count data a dynamic value

---

README.md
anonymizer_module/metrics_statistics/statistics_manager.py
collector_module/etc/settings.yaml
collector_module/opmon_collector/central_server_client.py
docs/collector_module.md

- Docs: Update README and collector module's documentation
- Feat: Add ability to disable certificate verification during connecting to central server
- Fix: Stop using dictionary unpacking for single fields to fix failing tests in anonymizer module
Refs: OPMONDEV-181

Ability to disable certificate verification during connecting to CS, update docs, and fix anonymizer failing tests

---

corrector_module/opmon_corrector/corrector_batch.py
corrector_module/opmon_corrector/corrector_worker.py
corrector_module/opmon_corrector/database_manager.py
corrector_module/opmon_corrector/document_manager.py
corrector_module/opmon_corrector/tests/test_corrector_batch.py
corrector_module/opmon_corrector/tests/test_document_manager.py
corrector_module/setup.py

Corrector is currently using multiprocessing only for raw data processing, and many tasks are preformed in a single main thread that can use only one CPU core and therefore negatively impact corrector throughput.
This pull request optimizes corrector to increase throughput. Additionally a check if processed document already exists in clean_data is added (this check existed before last corrector rewrite, but was broken since that time).
* Performing sanitise_document and correct_structure in worker threads instead of main thread.
* Deleting duplicates in threads instead of returning to_remove_queue and slowly processing that in main thread.
* Adding check if processed document already exists in clean_data (was broken after "matching of documents by xRequestId" commit).
* Using …

Corrector optimization

---

integration_tests/ci_reports/test_report_worker_CI.py
reports_module/opmon_reports/database_manager.py
reports_module/opmon_reports/report_manager.py

MongoDB sometimes selects incorrect index during report preparation queries. This results in inconsistent performance when some of the queries are unnecessarily slow. Using index hints helps MongoDB to select appropriate indexes for the queries.
This problem became especially obvious after upgrade to MongoDB v7, but the problem existed before upgrade too.
Additionally removing unnecessary DB requests to find the list of documents where client and service is the same subsystem.

Reports query optimization using index hints

---

reports_module/etc/settings.yaml
reports_module/opmon_reports/notification_manager.py
reports_module/opmon_reports/report_manager.py

Some users want to process report data, but generated PDF is not machine-readable. CSV format on the other hand can be easily imported into spreadsheets or processed by other tools.
This pull request is adding:
* CSV generation support
* optional configuration parameter for CSV generation
* REPORT_NAME_NO_EXT variable for email template

Adding support for CSV reports

---

reports_module/opmon_reports/report_manager.py
reports_module/opmon_reports/tests/test_report_manager.py

The top 5 charts for produced services are currently inaccurate. The row title displays the service name, but the value represents the highest value among the service's clients.
This pull request addresses this issue by summing all service client queries and calculating the correct average query duration.

Fix chart values in reports

---

.github/dependabot.yml
reports_module/setup.py

Latest `weasyprint` version `61.2` is not compatible with `pydyf` version `0.11.0`.
It causes error during runtime while generating PDFs.
This fix freezes `pydyf` version to `0.10.0`.
Refs: OPMONDEV-187

fix: Freeze pydyf's version in dependencies to fix reports during runtime

---

anonymizer_module/opmon_anonymizer/iio/mongodbmanager.py
corrector_module/opmon_corrector/database_manager.py
reports_module/opmon_reports/database_manager.py

`mongopy` [migration guide](https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html#collection-update-is-removed) states that the method `Collection.update` is removed and `Collection.update_one` (or `Collection.update_many`) should be used instead.
This PR fixes the code accordingly.
Refs: OPMONDEV-187

fix: Migrate mongopy's collection#update to collection#update_one

---

anonymizer_module/opmon_anonymizer/iio/postgresql_manager.py
anonymizer_module/opmon_anonymizer/tests/test_postgresql_manager.py

feat: as a Metrics User I want the database migration to check if fields are missing and add them for the anonymizer module

---

.github/dependabot.yml
anonymizer_module/setup.py
collector_module/setup.py
corrector_module/setup.py
opendata_module/setup.py
reports_module/setup.py

Added `ignore` sections for dependabot for dependencies:
- vcrpy>= 7.0.0
- setuptools">= 75.4.0
- urllib3 >= 2.3.0
because Python >=3.9 is required for those.
Bumped other dependency versions according to https://github.com/nordic-institute/X-Road-Metrics/pull/162.
Related dependabot PRs:
https://github.com/nordic-institute/X-Road-Metrics/pull/163 - rejected that one
https://github.com/nordic-institute/X-Road-Metrics/pull/162 - will reject that one as well

chore: ignore dependencies by dependabot; bump some dependency versions

---

collector_module/opmon_mongodb_maintenance/create_users.py
collector_module/opmon_mongodb_maintenance/tests/test_create_users.py
opendata_module/opmon_postgresql_maintenance/create_users.py
opendata_module/opmon_postgresql_maintenance/tests/test_create_users.py

fix: exclude backslashes from initially generated passwords

---

opendata_module/opmon_opendata/api/helpers.py
opendata_module/opmon_opendata/tests/test_helpers.py

Fixes for `daily_logs` endpoint:
1. JSON result: added outer element, namely - array notation (outer-most brackets - `[` and `]`)
2. JSON result: array elements are now separated with commas `{...}{...}{...}` -> `{...},{...},{...}`
3. In case when there are no results: instead of an empty archive producing error `There was an error while extracting <filename>: empty archive`, now the contents are an empty (but valid) JSON (`[]`).
Refs: OPMONDEV-193

fix: Fix JSON structure returned by 'daily_logs' endpoint

---

collector_module/opmon_collector/collector_worker.py
collector_module/opmon_collector/tests/test_collector_worker.py

RestPath field to be temporarily excluded (until X-Road v. 7.6.2 release)
Refs: OPMONDEV-194

fix: exclude 'restPath' field from being collected
